### ISSUE TITLE
Why Proxy?

### ISSUE THREAD

**Issue by mindplay-dk** [AlexxNB/storxy#3]
Just wondering, why do you need `Proxy` or `proxify` in `store`?

As far as I understand, `Proxy` is intended for situations where you need to proxy an unknown or dynamic set of properties? It looks like you're using it to define one property `$`, which you could have just done with `Object.defineProperty`, I think?

Maybe you have other plans for the future? Or maybe this was left from an earlier iteration of the library?

Just wondering. :-)

**Comment by AlexxNB** [comment]
Good question, thanks.

It is not true that proxying just one property. The `$` also may be an object and some values of this object also may be objects (and so on). So there is recursively proxifying.

For state manager it is very important to catch every objects mutation to run subscribers with new values. Proxy can catch almost all mutations like assigments, array pushing and so on. So it is the best choice, I think.

**Comment by mindplay-dk** [comment]
Ah, I see now. Thanks for explaining. 🙂

Unrelated, but you have an unused variable here:

https://github.com/AlexxNB/storxy/blob/1b7d6ca1a013ac0de9c5c9051b6686d3d3b3c66a/src/lib.js#L12

And feel free to close this issue. 🙂
